eureka:
  client:
    registry-fetch-interval-seconds: 20
    service-url:
      defaultZone: http://eureka9000.com:9000/eureka/,http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
  instance:
    prefer-ip-address: true
    home-page-url-path: ${server.servlet.context-path:}/
    status-page-url-path: ${server.servlet.context-path:}/swagger-ui.html
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
#rongly.love.name: 白素贞
